In [3]:
import numpy as np

In [4]:
a = np.array([[4,3],[2,1]])
b = np.array([[1,2],[3,4]])

In [7]:
a

array([[4, 3],
       [2, 1]])

In [8]:
b

array([[1, 2],
       [3, 4]])

In [9]:
a*b

array([[4, 6],
       [6, 4]])

In [10]:
a@b

array([[13, 20],
       [ 5,  8]])

In [12]:
np.arange(2)

array([0, 1])

In [14]:
np.random.rand()

0.2796512121525524

In [15]:
import pandas as pd